name: Run Script with Secrets

on:
  push:
    branches:
      - main 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check secrets (masked)
        run: |
          echo "GROQ_API_KEY is set: ${GROQ_API_KEY:+yes}"
          echo "NEWS_API_KEY is set: ${NEWS_API_KEY:+yes}"
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}

      - name: Run Streamlit app with secrets
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: streamlit run app.py --server.port 8501 --server.headless true
